# World Cup Matches Exercise

## Introduction

In this lab, we'll look at a dataset which contains information on World Cup matches. Let's use the Pandas commands learned in the previous lesson to learn more about our data!

## Objectives
You will be able to:
* Use some key Pandas methods
* Access DataFrame data by using `iloc` and `loc` 
* Filter rows of a DataFrame based on given conditions
* Create new columns in a DataFrame

## Load the file `'WorldCupMatches.csv'` as a DataFrame in Pandas.

In [2]:
import pandas as pd

In [28]:
df = pd.read_csv("WorldCupMatches.csv")
df.head()

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4,1,Mexico,,4444.0,3,0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201,1096,FRA,MEX
1,1930,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3,0,Belgium,,18346.0,2,0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201,1090,USA,BEL
2,1930,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2,1,Brazil,,24059.0,2,0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201,1093,YUG,BRA
3,1930,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3,1,Peru,,2549.0,1,0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201,1098,ROU,PER
4,1930,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1,0,France,,23409.0,0,0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201,1085,ARG,FRA

# Print the first 7 rows of the dataset

In [29]:
df.head(7)

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4,1,Mexico,,4444.0,3,0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201,1096,FRA,MEX
1,1930,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3,0,Belgium,,18346.0,2,0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201,1090,USA,BEL
2,1930,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2,1,Brazil,,24059.0,2,0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201,1093,YUG,BRA
3,1930,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3,1,Peru,,2549.0,1,0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201,1098,ROU,PER
4,1930,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1,0,France,,23409.0,0,0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201,1085,ARG,FRA
5,1930,16 Jul 1930 - 14:45,Group 1,Parque Central,Montevideo,Chile,3,0,Mexico,,9249.0,1,0,CRISTOPHE Henry (BEL),APHESTEGUY Martin (URU),LANGENUS Jean (BEL),201,1095,CHI,MEX
6,1930,17 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,4,0,Bolivia,,18306.0,0,0,MATEUCCI Francisco (URU),LOMBARDI Domingo (URU),WARNKEN Alberto (CHI),201,1092,YUG,BOL

# Last 4 rows of the df

In [30]:
df.tail(4)

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
848,2014,08 Jul 2014 - 17:00,Semi-finals,Estadio Mineirao,Belo Horizonte,Brazil,1,7,Germany,,58141.0,0,5,RODRIGUEZ Marco (MEX),TORRENTERA Marvin (MEX),QUINTERO Marcos (MEX),255955,300186474,BRA,GER
849,2014,09 Jul 2014 - 17:00,Semi-finals,Arena de Sao Paulo,Sao Paulo,Netherlands,0,0,Argentina,Argentina win on penalties (2 - 4),63267.0,0,0,C�neyt �AKIR (TUR),DURAN Bahattin (TUR),ONGUN Tarik (TUR),255955,300186490,NED,ARG
850,2014,12 Jul 2014 - 17:00,Play-off for third place,Estadio Nacional,Brasilia,Brazil,0,3,Netherlands,,68034.0,0,2,HAIMOUDI Djamel (ALG),ACHIK Redouane (MAR),ETCHIALI Abdelhak (ALG),255957,300186502,BRA,NED
851,2014,13 Jul 2014 - 16:00,Final,Estadio do Maracana,Rio De Janeiro,Germany,1,0,Argentina,Germany win after extra time,74738.0,0,0,Nicola RIZZOLI (ITA),Renato FAVERANI (ITA),Andrea STEFANI (ITA),255959,300186501,GER,ARG

## Get a concise summary of the data using `.info()`.

In [31]:
# Print a concise summary of df
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 852 entries, 0 to 851
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Year                  852 non-null    int64
 1   Datetime              852 non-null    object
 2   Stage                 852 non-null    object
 3   Stadium               852 non-null    object
 4   City                  852 non-null    object
 5   Home Team Name        852 non-null    object
 6   Home Team Goals       852 non-null    int64
 7   Away Team Goals       852 non-null    int64
 8   Away Team Name        852 non-null    object
 9   Win conditions        852 non-null    object
 10  Attendance            850 non-null    float64
 11  Half-time Home Goals  852 non-null    int64
 12  Half-time Away Goals  852 non-null    int64
 13  Referee               852 non-null    object
 14  Assistant 1           852 non-null    object
 15  Assistant 2           852 non-null    object
 16  RoundID               852 non-null    int64
 17  MatchID               852 non-null    int64
 18  Home Team Initials    852 non-null    object
 19  Away Team Initials    852 non-null    object
dtypes: float64(1), int64(7), object(12)
memory usage: 133.2+ KB

**Obtain a tuple representing the number of rows and number of columns**

In [32]:
# Print the number of rows and columns in df
df.shape

(852, 20)

In [33]:
df.columns

Index(['Year', 'Datetime', 'Stage', 'Stadium', 'City', 'Home Team Name',
       'Home Team Goals', 'Away Team Goals', 'Away Team Name',
       'Win conditions', 'Attendance', 'Half-time Home Goals',
       'Half-time Away Goals', 'Referee', 'Assistant 1', 'Assistant 2',
       'RoundID', 'MatchID', 'Home Team Initials', 'Away Team Initials'],
      dtype='object')

# Selecting information from DataFrame

When looking at the DataFrame's `.head()`, you might have noticed that the games are structured chronologically in the DataFrame.

Use the right selection method to print all the information from the 3rd to the 5th game.

In [34]:
# Print rows 3 through 5
df.iloc[3:6]

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
3,1930,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3,1,Peru,,2549.0,1,0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201,1098,ROU,PER
4,1930,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1,0,France,,23409.0,0,0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201,1085,ARG,FRA
5,1930,16 Jul 1930 - 14:45,Group 1,Parque Central,Montevideo,Chile,3,0,Mexico,,9249.0,1,0,CRISTOPHE Henry (BEL),APHESTEGUY Martin (URU),LANGENUS Jean (BEL),201,1095,CHI,MEX

# Now, print all the info from game 5-9, but we're only interested in printing out the, "Home Team Name" and the, "Away Team Name."

In [37]:
df.loc[5:9,["Home Team Name","Away Team Name"]]

  Home Team Name Away Team Name
5          Chile         Mexico
6     Yugoslavia        Bolivia
7            USA       Paraguay
8        Uruguay           Peru
9          Chile         France

# Next, we'd like the information on all the games played in Group 3 for the 1950 World Cup.

In [45]:
df.loc[(df["Year"] == 1950) & (df["Stage"] == "Group 3")]

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
56,1950,25 Jun 1950 - 15:00,Group 3,Pacaembu,Sao Paulo,Sweden,3,2,Italy,,36502.0,2,1,LUTZ Jean (SUI),BERANEK Alois (AUT),TEJADA Carlos (MEX),208,1219,SWE,ITA
61,1950,29 Jun 1950 - 15:30,Group 3,Durival de Brito,Curitiba,Sweden,2,2,Paraguay,,7903.0,2,1,MITCHELL Robert (SCO),LEMESIC Leo (YUG),GARCIA Prudencio (USA),208,1228,SWE,PAR
65,1950,02 Jul 1950 - 15:00,Group 3,Pacaembu,Sao Paulo,Italy,2,0,Paraguay,,25811.0,1,0,ELLIS Arthur (ENG),GARCIA Prudencio (USA),DE LA SALLE Charles (FRA),208,1218,ITA,PAR

# Or

In [49]:
df[(df["Year"] == 1950) & (df["Stage"] == "Group 3")]

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
56,1950,25 Jun 1950 - 15:00,Group 3,Pacaembu,Sao Paulo,Sweden,3,2,Italy,,36502.0,2,1,LUTZ Jean (SUI),BERANEK Alois (AUT),TEJADA Carlos (MEX),208,1219,SWE,ITA
61,1950,29 Jun 1950 - 15:30,Group 3,Durival de Brito,Curitiba,Sweden,2,2,Paraguay,,7903.0,2,1,MITCHELL Robert (SCO),LEMESIC Leo (YUG),GARCIA Prudencio (USA),208,1228,SWE,PAR
65,1950,02 Jul 1950 - 15:00,Group 3,Pacaembu,Sao Paulo,Italy,2,0,Paraguay,,25811.0,1,0,ELLIS Arthur (ENG),GARCIA Prudencio (USA),DE LA SALLE Charles (FRA),208,1218,ITA,PAR

**Let's repeat the command above, but now we only want to print out the attendance column for the Group 3 games.**

You can combine conditions like this:

`df[(condition1) | (condition2)]`  -> Returns rows where either condition is true

`df[(condition1) & (condition2)]`  -> Returns rows where both conditions are true

# Print the attendance column for games played in 1950 for group 3

In [52]:
df.loc[(df["Year"] == 1950) & (df["Stage"] == "Group 3"), "Attendance"]

56    36502.0
61     7903.0
65    25811.0
Name: Attendance, dtype: float64

## Throughout the entire history of the World Cup, how many home games were played by the Netherlands?

In [54]:
df.head()

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4,1,Mexico,,4444.0,3,0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201,1096,FRA,MEX
1,1930,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3,0,Belgium,,18346.0,2,0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201,1090,USA,BEL
2,1930,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2,1,Brazil,,24059.0,2,0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201,1093,YUG,BRA
3,1930,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3,1,Peru,,2549.0,1,0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201,1098,ROU,PER
4,1930,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1,0,France,,23409.0,0,0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201,1085,ARG,FRA

In [58]:
Netherlands_Homegames = df[df["Home Team Name"] == "Netherlands"]
Netherlands_Homegames.head()
len(Netherlands_Homegames)  # We can simply see here 32 Home games were played by the Netherlands

32

# How many games were played by the Netherlands in total?

In [61]:
Total_Neth_games = Netherlands_Homegames + df[df["Away Team Name"] == "Netherlands"]
len(Total_Neth_games)

54

# Next, let's try and figure out how many games the USA played in the 2014 World Cup.

In [63]:
Total_US_games = df.loc[(df["Year"] == 2014) & (df["Home Team Name"] == "USA") | (df["Away Team Name"] == "USA")]
len(Total_US_games)

21

# Now, let's try to find out how many countries participated in the 1986 World Cup.

In [70]:
games_1986 = df[df["Year"]==1986]  # Or games_1986 = df.loc[(df["Year"]==1986)]

home = list(games_1986['Home Team Name'].unique())
away = list(games_1986['Away Team Name'].unique())
print("Total Number of Countries in the 1986 WorldCup were " ,len(home) , "countries")
home += away
print("Total Number of Home Teams were " ,len(home) , "countries")
print("Total Number of Away Teams were " ,len(set(home)), "countries")

Total Number of Countries in the 1986 WorldCup were  24 countries
Total Number of Home Teams were  48 countries
Total Number of Away Teams were  24 countries

In [67]:
len(home)

48

In [68]:
len(away)

24

# In World Cup history, how matches had more than 5 goals in total?

In [73]:
total_goals = df.loc[df["Home Team Goals"] + df["Away Team Goals"]]

In [74]:
len(total_goals)

852

In [79]:
# Let's Create a new column called total games from the above
df["total_goals"] = df["Home Team Goals"] + df["Away Team Goals"]

In [83]:
print(len(df["total_goals"] <=5))

852

## Changing values and creating new columns

+ With the information you currently have in your `df`, create a new column, "Half-time Goals."

In [86]:
df["Half-time Goals"] = df["Half-time Home Goals"] + df["Half-time Away Goals"]
df["Half-time Goals"].head()

0    3
1    2
2    2
3    1
4    0
Name: Half-time Goals, dtype: int64

## You'll notice that for Korea, there are records for both North-Korea (Korea DPR) and South-Korea (Korea Republic).

In [87]:
df.loc[df["Home Team Name"].str.contains("Korea") , "Home Team Name"]

179         Korea DPR
187         Korea DPR
374    Korea Republic
386    Korea Republic
434    Korea Republic
444    Korea Republic
480    Korea Republic
524    Korea Republic
593    Korea Republic
609    Korea Republic
635    Korea Republic
642    Korea Republic
655    Korea Republic
710    Korea Republic
753         Korea DPR
802    Korea Republic
818    Korea Republic
Name: Home Team Name, dtype: object

+ Imagine that, for some reason, we simply want Korea listed as one entry, so we want to replace every "Home Team Name" and "Away Team Name" entry that contains "Korea" to simply "Korea". In the same way, we want to change the columns "Home Team Initials" and "Away Team Initials" to NSK (North & South Korea) instead of "KOR" and "PRK".

# Changing the home and away team names

In [88]:
df.loc[df["Home Team Name"] == "Korea DPR", "Home Team Name"] = "Korea"
df.loc[df["Home Team Name"] == "Korea Republic", "Home Team Name"] = "Korea"
df.loc[df["Away Team Name"] == "Korea DPR", "Away Team Name"] = "Korea"
df.loc[df["Away Team Name"] == "Korea Republic", "Away Team Name"] = "Korea"

# Changing the hometeam and the away team initails

In [ ]:
df.loc[df["Home Team Initials"] == "KOR", "Home Team Initials"] = "NSK"
df.loc[df["Home Team Initials"] == "KOR", "Home Team Initials"] = "NSK"
df.loc[df["Away Team Initials"] == "PRK", "Away Team Initials"] = "NSK"
df.loc[df["Away Team Initials"] == "PRK", "Away Team Initials"] = "NSK"

# Let's Check Our Results

In [89]:
df.loc[df['Home Team Name'].str.contains('Korea')]

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,...,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials,total_goals,Half-time Goals
179,1966,15 Jul 1966 - 19:30,Group 4,Ayresome Park,Middlesbrough,Korea,1,1,Chile,,...,1,KANDIL Aly Hussein (EGY),CRAWFORD William (SCO),FINNEY Jim (ENG),238,1609,PRK,CHI,2,1
187,1966,19 Jul 1966 - 19:30,Group 4,Ayresome Park,Middlesbrough,Korea,1,0,Italy,,...,0,SCHWINTE Pierre (FRA),ADAIR John (NIR),TAYLOR John (ENG),238,1679,PRK,ITA,1,1
374,1986,05 Jun 1986 - 16:00,Group A,Estadio Ol�mpico Universitario,Mexico City,Korea,1,1,Bulgaria,,...,1,AL SHANAR Fallaj Khuzam (KSA),IGNA Ioan (ROU),BUTENKO Valeri (RUS),308,460,KOR,BUL,2,1
386,1986,10 Jun 1986 - 12:00,Group A,Cuauhtemoc,Puebla,Korea,2,3,Italy,,...,1,SOCHA David (USA),URREA Joaquin (MEX),AL SHARIF Jamal (SYR),308,643,KOR,ITA,5,1
434,1990,17 Jun 1990 - 21:00,Group E,Dacia Arena,Udine,Korea,1,3,Spain,,...,1,JACOME GUERRERO Elias V. (ECU),MAGNI Pierluigi (ITA),LOUSTAU Juan (ARG),322,175,KOR,ESP,4,2
444,1990,21 Jun 1990 - 17:00,Group E,Friuli,Udine,Korea,0,1,Uruguay,,...,0,LANESE Tullio (ITA),DIRAMBA Jean Fidele (GAB),JOUINI Neji (TUN),322,290,KOR,URU,1,0
480,1994,23 Jun 1994 - 19:30,Group C,Foxboro Stadium,Boston,Korea,0,0,Bolivia,,...,0,MOTTRAM Leslie (SCO),MATTHYS Luc (BEL),EVERSTIG Mikael (SWE),337,3065,KOR,BOL,0,0
524,1998,13 Jun 1998 - 17:30,Group E,Stade de Gerland,Lyon,Korea,1,3,Mexico,,...,0,BENKO Gunter (AUT),FRED Lencie (VAN),SCHNEIDER Erich (GER),1014,8732,KOR,MEX,4,1
593,2002,04 Jun 2002 - 20:30,Group D,Busan Asiad Main Stadium,Busan,Korea,2,0,Poland,,...,0,RUIZ Oscar (COL),DORIRI Elise (VAN),LINDBERG Leif (SWE),43950100,43950014,KOR,POL,2,1
609,2002,10 Jun 2002 - 15:30,Group D,Daegu World Cup Stadium,Daegu,Korea,1,1,USA,,...,1,MEIER Urs (SUI),BEREUTER Egon (AUT),TOMUSANGE Ali (UGA),43950100,43950030,KOR,USA,2,1
635,2002,18 Jun 2002 - 20:30,Round of 16,Daejeon World Cup Stadium,Daejeon,Korea,2,1,Italy,Win on Golden Goal,...,0,MORENO Byron (ECU),RATTALINO Jorge (ARG),SZEKELY Ferenc (HUN),43950200,43950056,KOR,ITA,3,0
642,2002,29 Jun 2002 - 20:00,Third place,Daegu World Cup Stadium,Daegu,Korea,2,3,Turkey,,...,3,MANE Saad (KUW),ALTRAIFI Ali (KSA),VERGARA Hector (CAN),43950500,43950063,KOR,TUR,5,4
655,2006,13 Jun 2006 - 15:00,Group G,"FIFA World Cup Stadium, Frankfurt",Frankfurt/Main,Korea,2,1,Togo,,...,1,POLL Graham (ENG),SHARP Philip (ENG),TURNER Glenn (ENG),97410100,97410014,KOR,TOG,3,1
710,2010,12 Jun 2010 - 13:30,Group B,Port Elizabeth Stadium,Nelson Mandela Bay/Port Elizabeth,Korea,2,0,Greece,,...,0,HESTER Michael (NZL),HINTZ Jan Hendrik (NZL),MAKASINI Tevita (TGA),249722,300061459,KOR,GRE,2,1
753,2010,25 Jun 2010 - 16:00,Group G,Mbombela Stadium,Nelspruit,Korea,0,3,C�te d'Ivoire,,...,2,Alberto UNDIANO MALLENCO (ESP),MARTINEZ Fermin (ESP),YUSTE Juan (ESP),249722,300061486,PRK,CIV,3,2
802,2014,22 Jun 2014 - 16:00,Group H,Estadio Beira-Rio,Porto Alegre,Korea,2,4,Algeria,,...,3,ROLDAN Wilmar (COL),DIAZ Eduardo (COL),LESCANO Christian (ECU),255931,300186495,KOR,ALG,6,3
818,2014,26 Jun 2014 - 17:00,Group H,Arena de Sao Paulo,Sao Paulo,Korea,0,1,Belgium,,...,0,Ben WILLIAMS (AUS),CREAM Matthew (AUS),ANAZ Hakan (AUS),255931,300186480,KOR,BEL,1,0

## Summary

+ In this exercise, you learned how to access data within Pandas!